// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  13 Apr 2020 21.08.37
// ======================================================


import Foundation


class DataExplorers {
    var name : String? = nil; // Explorer
    var grade : String? = nil; // 
    var shift : String? = nil; // 
    var role : String? = nil; // 
    var foto : String? = nil; // 
    var wantLearn : String? = nil; // 
    var help : String? = nil; // 
}