// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  13 Apr 2020 21.08.37
// ======================================================


import Foundation


private let AUTO_PLIST_DATAEXPLORERS_PATH = Bundle.main.path(forResource: "DataExplorers", ofType: "plist")

private let AUTO_PLIST_DATAEXPLORERS_INDEX_NAME = 0   // Explorer
private let AUTO_PLIST_DATAEXPLORERS_INDEX_GRADE = 1   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_SHIFT = 2   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_ROLE = 3   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_FOTO = 4   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_WANTLEARN = 5   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_HELP = 6   // 


class ExplorerManager {

    public static let sharedManager = ExplorerManager()
    private init(){}

    private var _dataExplorerss = [DataExplorers]()

    func allDataExplorerss() -> [DataExplorers]{

        if _dataExplorerss.count > 0 {
            return _dataExplorerss
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_DATAEXPLORERS_PATH!) {

            for array in allDatas {
                guard let array = array as? [AnyObject] else {continue}

                let dataExplorers = DataExplorers()
                dataExplorers.name = array[AUTO_PLIST_DATAEXPLORERS_INDEX_NAME] as? String // Explorer
                dataExplorers.grade = array[AUTO_PLIST_DATAEXPLORERS_INDEX_GRADE] as? String // 
                dataExplorers.shift = array[AUTO_PLIST_DATAEXPLORERS_INDEX_SHIFT] as? String // 
                dataExplorers.role = array[AUTO_PLIST_DATAEXPLORERS_INDEX_ROLE] as? String // 
                dataExplorers.foto = array[AUTO_PLIST_DATAEXPLORERS_INDEX_FOTO] as? String // 
                dataExplorers.wantLearn = array[AUTO_PLIST_DATAEXPLORERS_INDEX_WANTLEARN] as? String // 
                dataExplorers.help = array[AUTO_PLIST_DATAEXPLORERS_INDEX_HELP] as? String // 
                _dataExplorerss.append(dataExplorers)
            }
        }
        return _dataExplorerss
    }
}